#pragma once
#include "utility/macros.h"

#include "external/better_enums/enum.h"

#include <cstdint>

CLANG_IGNORE_WARNING_PUSH("-Wglobal-constructors")
BETTER_ENUM(TokenType, uint8_t,
    UNKNOWN,
    IDENTIFIER,
    KEYWORD,
    KW_NULL,
    KW_TRUE,
    KW_FALSE,
    BUILT_IN_TYPE,

    LIT_INTEGER,
    LIT_FLOATING_POINT,
    LIT_RUNE,
    LIT_STRING,

    OP_PLUS,
    OP_MINUS,
    OP_MUL,
    OP_DIV,
    OP_MOD,
    OP_INC,
    OP_DEC,
    OP_RANGE,
    OP_LOGICAL_NOT,
    OP_EQUAL,
    OP_NOT_EQUAL,
    OP_GREATER,
    OP_GREATER_EQUAL,
    OP_LESS,
    OP_LESS_EQUAL,
    OP_LOGICAL_AND,
    OP_LOGICAL_OR,
    OP_BITWISE_NOT,
    OP_BITWISE_AND,
    OP_BITWISE_OR,
    OP_BITWISE_XOR,
    OP_BITWISE_LSHIFT,
    OP_BITWISE_RSHIFT,
    OP_ASSIGN,
    OP_ASSIGN_ADD,
    OP_ASSIGN_SUB,
    OP_ASSIGN_MUL,
    OP_ASSIGN_DIV,
    OP_ASSIGN_MOD,
    OP_ASSIGN_AND,
    OP_ASSIGN_OR,
    OP_ASSIGN_XOR,
    OP_ASSIGN_LSHIFT,
    OP_ASSIGN_RSHIFT,
    OP_ADDRESS_OF,

    LPAREN,
    RPAREN,
    LBRACKET,
    RBRACKET,
    COLON,
    SEMICOLON,
    COMMA,
    DOT,
    NEWLINE,
    COMMENT,
    TOKEN_EOF
);
CLANG_IGNORE_WARNING_POP
