LINE:COL  | TYPE             | VALUE
   1:1    | IDENTIFIER       | x
   1:3    | OP_ASSIGN        | =
   1:5    | LIT_INTEGER      | 42
   1:7    | TERMINATOR       | \n
   2:1    | IDENTIFIER       | value
   2:7    | COLON            | :
   2:9    | T_I32            | i32
   2:13   | OP_ASSIGN        | =
   2:15   | LIT_INTEGER      | 123
   2:18   | TERMINATOR       | \n
   3:1    | IDENTIFIER       | byte_value
   3:12   | COLON            | :
   3:14   | T_U8             | u8
   3:17   | OP_ASSIGN        | =
   3:19   | LIT_INTEGER      | 255
   3:22   | TOKEN_EOF        | 
